### ISSUE TITLE
Error running on Python 3.5 Windows/MacOS

### ISSUE THREAD

**Issue by allanon911** [skiplagged/pokemongo-python#7]
Tried both types of login - via trainer club and google and neither works

post exception Traceback (most recent call last):
  File "C:\Users\xxx\Google Drive\private\Apps\pokemongo-python-master\skiplagged.py", line 89, in _call
    return json.loads(r.content)
  File "C:\NO_BACKUP\python\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by aktarer** [comment]
It seems python handles json differently on windows. You can try our PHP version, which just needs curl: https://github.com/skiplagged/pokemongo-php

**Comment by Ashex1** [comment]
Try changing this on line 31:

```python
print "exception:", e
```

to this:

``python
print("Exception: {0} {1}".format(e.message, e.args))
```

**Comment by januri** [comment]
try with python 2.7.x
